set sdc_version 2.2
set_units -time ns -capacitance pF -resistance kOhm
# apb_uart.sdc  —  generated by Ṛta  2026-08-13
# NOTE: Review all values before using in synthesis.

# ── Clock definitions ───────────────────────────────────────────
create_clock -name clk -period 10.000 [get_ports clk]
create_clock -name clk_div2 -period 5.000 [get_ports clk_div2]

# ── Clock attributes ────────────────────────────────────────────
set_clock_uncertainty -setup 0.15 [get_clocks clk]
set_clock_uncertainty -hold  0.075 [get_clocks clk]
set_clock_uncertainty -setup 0.15 [get_clocks clk_div2]
set_clock_uncertainty -hold  0.075 [get_clocks clk_div2]
set_propagated_clock [get_clocks {clk clk_div2}]

# ── CDC — asynchronous clock groups ────────────────────────────
set_clock_groups -asynchronous \
  -group [get_clocks clk] \
  -group [get_clocks clk_div2]

# ── I/O constraints ─────────────────────────────────────────────
set_input_delay -max 1.2 -clock clk \
  [remove_from_collection [all_inputs] [get_ports {clk clk_div2 rst_n}]]
set_input_delay -min 0.4 -clock clk \
  [remove_from_collection [all_inputs] [get_ports {clk clk_div2 rst_n}]]
set_output_delay -max 1.5 -clock clk [all_outputs]
set_output_delay -min 0.5 -clock clk [all_outputs]
set_driving_cell -lib_cell BUF_X4 -pin Z \
  [remove_from_collection [all_inputs] [get_ports {clk clk_div2}]]
set_load 0.05 [all_outputs]

# ── Design rule constraints ─────────────────────────────────────
set_max_fanout     20 [all_inputs]
set_max_transition 0.2 [all_nets]
set_max_capacitance 0.1 [all_nets]

# ── Operating conditions ────────────────────────────────────────
set_operating_conditions -max SS_0P72V_16C

# ── Timing derate (AOCV) ────────────────────────────────────────
set_timing_derate -late  -cell_delay 0.92  [all_nets]
set_timing_derate -early -cell_delay 1.08 [all_nets]
set_timing_derate -late  -net_delay  1.0   [all_nets]
set_timing_derate -early -net_delay  1.0  [all_nets]

# ── Ideal networks ──────────────────────────────────────────────
set_ideal_network [get_ports rst_n]
set_false_path -from [get_ports rst_n]

# ── Scan / DFT ──────────────────────────────────────────────────
set_case_analysis 0 [get_ports scan_en]
set_ideal_network [get_ports scan_en]
