# Generated large design: 24 clock domains, many exceptions.
set sdc_version 2.2
set_units -time ns -capacitance pF
create_clock -name clk_0 -period 5.0 [get_ports clk_0]
create_clock -name clk_1 -period 6.0 [get_ports clk_1]
create_clock -name clk_2 -period 7.0 [get_ports clk_2]
create_clock -name clk_3 -period 8.0 [get_ports clk_3]
create_clock -name clk_4 -period 5.0 [get_ports clk_4]
create_clock -name clk_5 -period 6.0 [get_ports clk_5]
create_clock -name clk_6 -period 7.0 [get_ports clk_6]
create_clock -name clk_7 -period 8.0 [get_ports clk_7]
create_clock -name clk_8 -period 5.0 [get_ports clk_8]
create_clock -name clk_9 -period 6.0 [get_ports clk_9]
create_clock -name clk_10 -period 7.0 [get_ports clk_10]
create_clock -name clk_11 -period 8.0 [get_ports clk_11]
create_clock -name clk_12 -period 5.0 [get_ports clk_12]
create_clock -name clk_13 -period 6.0 [get_ports clk_13]
create_clock -name clk_14 -period 7.0 [get_ports clk_14]
create_clock -name clk_15 -period 8.0 [get_ports clk_15]
create_clock -name clk_16 -period 5.0 [get_ports clk_16]
create_clock -name clk_17 -period 6.0 [get_ports clk_17]
create_clock -name clk_18 -period 7.0 [get_ports clk_18]
create_clock -name clk_19 -period 8.0 [get_ports clk_19]
create_clock -name clk_20 -period 5.0 [get_ports clk_20]
create_clock -name clk_21 -period 6.0 [get_ports clk_21]
create_clock -name clk_22 -period 7.0 [get_ports clk_22]
create_clock -name clk_23 -period 8.0 [get_ports clk_23]

# clock groups (all async pairs)
set_clock_groups -asynchronous -group [get_clocks clk_0] -group [get_clocks clk_1]
set_clock_groups -asynchronous -group [get_clocks clk_2] -group [get_clocks clk_3]
set_clock_groups -asynchronous -group [get_clocks clk_4] -group [get_clocks clk_5]
set_clock_groups -asynchronous -group [get_clocks clk_6] -group [get_clocks clk_7]
set_clock_groups -asynchronous -group [get_clocks clk_8] -group [get_clocks clk_9]
set_clock_groups -asynchronous -group [get_clocks clk_10] -group [get_clocks clk_11]
set_clock_groups -asynchronous -group [get_clocks clk_12] -group [get_clocks clk_13]
set_clock_groups -asynchronous -group [get_clocks clk_14] -group [get_clocks clk_15]
set_clock_groups -asynchronous -group [get_clocks clk_16] -group [get_clocks clk_17]
set_clock_groups -asynchronous -group [get_clocks clk_18] -group [get_clocks clk_19]
set_clock_groups -asynchronous -group [get_clocks clk_20] -group [get_clocks clk_21]
set_clock_groups -asynchronous -group [get_clocks clk_22] -group [get_clocks clk_23]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_0]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_1]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_2]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_3]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_4]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_5]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_6]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_7]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_8]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_9]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_10]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_11]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_12]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_13]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_14]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_15]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_16]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_17]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_18]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_19]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_20]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_21]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_22]
set_clock_uncertainty -setup 0.15 -hold 0.07 [get_clocks clk_23]

# IO delays
set_input_delay -max 1.00 -min 0.2 -clock clk_0 [get_ports din_0[*]]
set_output_delay -max 1.00 -min 0.2 -clock clk_0 [get_ports dout_0[*]]
set_input_delay -max 1.10 -min 0.2 -clock clk_1 [get_ports din_1[*]]
set_output_delay -max 1.10 -min 0.2 -clock clk_1 [get_ports dout_1[*]]
set_input_delay -max 1.20 -min 0.2 -clock clk_2 [get_ports din_2[*]]
set_output_delay -max 1.20 -min 0.2 -clock clk_2 [get_ports dout_2[*]]
set_input_delay -max 1.30 -min 0.2 -clock clk_3 [get_ports din_3[*]]
set_output_delay -max 1.30 -min 0.2 -clock clk_3 [get_ports dout_3[*]]
set_input_delay -max 1.40 -min 0.2 -clock clk_4 [get_ports din_4[*]]
set_output_delay -max 1.40 -min 0.2 -clock clk_4 [get_ports dout_4[*]]
set_input_delay -max 1.50 -min 0.2 -clock clk_5 [get_ports din_5[*]]
set_output_delay -max 1.50 -min 0.2 -clock clk_5 [get_ports dout_5[*]]
set_input_delay -max 1.60 -min 0.2 -clock clk_6 [get_ports din_6[*]]
set_output_delay -max 1.60 -min 0.2 -clock clk_6 [get_ports dout_6[*]]
set_input_delay -max 1.70 -min 0.2 -clock clk_7 [get_ports din_7[*]]
set_output_delay -max 1.70 -min 0.2 -clock clk_7 [get_ports dout_7[*]]
set_input_delay -max 1.80 -min 0.2 -clock clk_8 [get_ports din_8[*]]
set_output_delay -max 1.80 -min 0.2 -clock clk_8 [get_ports dout_8[*]]
set_input_delay -max 1.90 -min 0.2 -clock clk_9 [get_ports din_9[*]]
set_output_delay -max 1.90 -min 0.2 -clock clk_9 [get_ports dout_9[*]]
set_input_delay -max 2.00 -min 0.2 -clock clk_10 [get_ports din_10[*]]
set_output_delay -max 2.00 -min 0.2 -clock clk_10 [get_ports dout_10[*]]
set_input_delay -max 2.10 -min 0.2 -clock clk_11 [get_ports din_11[*]]
set_output_delay -max 2.10 -min 0.2 -clock clk_11 [get_ports dout_11[*]]
set_input_delay -max 2.20 -min 0.2 -clock clk_12 [get_ports din_12[*]]
set_output_delay -max 2.20 -min 0.2 -clock clk_12 [get_ports dout_12[*]]
set_input_delay -max 2.30 -min 0.2 -clock clk_13 [get_ports din_13[*]]
set_output_delay -max 2.30 -min 0.2 -clock clk_13 [get_ports dout_13[*]]
set_input_delay -max 2.40 -min 0.2 -clock clk_14 [get_ports din_14[*]]
set_output_delay -max 2.40 -min 0.2 -clock clk_14 [get_ports dout_14[*]]
set_input_delay -max 2.50 -min 0.2 -clock clk_15 [get_ports din_15[*]]
set_output_delay -max 2.50 -min 0.2 -clock clk_15 [get_ports dout_15[*]]
set_input_delay -max 2.60 -min 0.2 -clock clk_16 [get_ports din_16[*]]
set_output_delay -max 2.60 -min 0.2 -clock clk_16 [get_ports dout_16[*]]
set_input_delay -max 2.70 -min 0.2 -clock clk_17 [get_ports din_17[*]]
set_output_delay -max 2.70 -min 0.2 -clock clk_17 [get_ports dout_17[*]]
set_input_delay -max 2.80 -min 0.2 -clock clk_18 [get_ports din_18[*]]
set_output_delay -max 2.80 -min 0.2 -clock clk_18 [get_ports dout_18[*]]
set_input_delay -max 2.90 -min 0.2 -clock clk_19 [get_ports din_19[*]]
set_output_delay -max 2.90 -min 0.2 -clock clk_19 [get_ports dout_19[*]]
set_input_delay -max 3.00 -min 0.2 -clock clk_20 [get_ports din_20[*]]
set_output_delay -max 3.00 -min 0.2 -clock clk_20 [get_ports dout_20[*]]
set_input_delay -max 3.10 -min 0.2 -clock clk_21 [get_ports din_21[*]]
set_output_delay -max 3.10 -min 0.2 -clock clk_21 [get_ports dout_21[*]]
set_input_delay -max 3.20 -min 0.2 -clock clk_22 [get_ports din_22[*]]
set_output_delay -max 3.20 -min 0.2 -clock clk_22 [get_ports dout_22[*]]
set_input_delay -max 3.30 -min 0.2 -clock clk_23 [get_ports din_23[*]]
set_output_delay -max 3.30 -min 0.2 -clock clk_23 [get_ports dout_23[*]]

# exceptions
set_false_path -from [get_pins U_A_0/Q] -to [get_pins U_B_0/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_0] -to [get_cells R_B_0]
set_false_path -from [get_pins U_A_1/Q] -to [get_pins U_B_1/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_1] -to [get_cells R_B_1]
set_false_path -from [get_pins U_A_2/Q] -to [get_pins U_B_2/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_2] -to [get_cells R_B_2]
set_false_path -from [get_pins U_A_3/Q] -to [get_pins U_B_3/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_3] -to [get_cells R_B_3]
set_false_path -from [get_pins U_A_4/Q] -to [get_pins U_B_4/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_4] -to [get_cells R_B_4]
set_false_path -from [get_pins U_A_5/Q] -to [get_pins U_B_5/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_5] -to [get_cells R_B_5]
set_false_path -from [get_pins U_A_6/Q] -to [get_pins U_B_6/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_6] -to [get_cells R_B_6]
set_false_path -from [get_pins U_A_7/Q] -to [get_pins U_B_7/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_7] -to [get_cells R_B_7]
set_false_path -from [get_pins U_A_8/Q] -to [get_pins U_B_8/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_8] -to [get_cells R_B_8]
set_false_path -from [get_pins U_A_9/Q] -to [get_pins U_B_9/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_9] -to [get_cells R_B_9]
set_false_path -from [get_pins U_A_10/Q] -to [get_pins U_B_10/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_10] -to [get_cells R_B_10]
set_false_path -from [get_pins U_A_11/Q] -to [get_pins U_B_11/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_11] -to [get_cells R_B_11]
set_false_path -from [get_pins U_A_12/Q] -to [get_pins U_B_12/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_12] -to [get_cells R_B_12]
set_false_path -from [get_pins U_A_13/Q] -to [get_pins U_B_13/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_13] -to [get_cells R_B_13]
set_false_path -from [get_pins U_A_14/Q] -to [get_pins U_B_14/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_14] -to [get_cells R_B_14]
set_false_path -from [get_pins U_A_15/Q] -to [get_pins U_B_15/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_15] -to [get_cells R_B_15]
set_false_path -from [get_pins U_A_16/Q] -to [get_pins U_B_16/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_16] -to [get_cells R_B_16]
set_false_path -from [get_pins U_A_17/Q] -to [get_pins U_B_17/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_17] -to [get_cells R_B_17]
set_false_path -from [get_pins U_A_18/Q] -to [get_pins U_B_18/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_18] -to [get_cells R_B_18]
set_false_path -from [get_pins U_A_19/Q] -to [get_pins U_B_19/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_19] -to [get_cells R_B_19]
set_false_path -from [get_pins U_A_20/Q] -to [get_pins U_B_20/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_20] -to [get_cells R_B_20]
set_false_path -from [get_pins U_A_21/Q] -to [get_pins U_B_21/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_21] -to [get_cells R_B_21]
set_false_path -from [get_pins U_A_22/Q] -to [get_pins U_B_22/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_22] -to [get_cells R_B_22]
set_false_path -from [get_pins U_A_23/Q] -to [get_pins U_B_23/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_23] -to [get_cells R_B_23]
set_false_path -from [get_pins U_A_24/Q] -to [get_pins U_B_24/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_24] -to [get_cells R_B_24]
set_false_path -from [get_pins U_A_25/Q] -to [get_pins U_B_25/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_25] -to [get_cells R_B_25]
set_false_path -from [get_pins U_A_26/Q] -to [get_pins U_B_26/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_26] -to [get_cells R_B_26]
set_false_path -from [get_pins U_A_27/Q] -to [get_pins U_B_27/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_27] -to [get_cells R_B_27]
set_false_path -from [get_pins U_A_28/Q] -to [get_pins U_B_28/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_28] -to [get_cells R_B_28]
set_false_path -from [get_pins U_A_29/Q] -to [get_pins U_B_29/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_29] -to [get_cells R_B_29]
set_false_path -from [get_pins U_A_30/Q] -to [get_pins U_B_30/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_30] -to [get_cells R_B_30]
set_false_path -from [get_pins U_A_31/Q] -to [get_pins U_B_31/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_31] -to [get_cells R_B_31]
set_false_path -from [get_pins U_A_32/Q] -to [get_pins U_B_32/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_32] -to [get_cells R_B_32]
set_false_path -from [get_pins U_A_33/Q] -to [get_pins U_B_33/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_33] -to [get_cells R_B_33]
set_false_path -from [get_pins U_A_34/Q] -to [get_pins U_B_34/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_34] -to [get_cells R_B_34]
set_false_path -from [get_pins U_A_35/Q] -to [get_pins U_B_35/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_35] -to [get_cells R_B_35]
set_false_path -from [get_pins U_A_36/Q] -to [get_pins U_B_36/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_36] -to [get_cells R_B_36]
set_false_path -from [get_pins U_A_37/Q] -to [get_pins U_B_37/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_37] -to [get_cells R_B_37]
set_false_path -from [get_pins U_A_38/Q] -to [get_pins U_B_38/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_38] -to [get_cells R_B_38]
set_false_path -from [get_pins U_A_39/Q] -to [get_pins U_B_39/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_39] -to [get_cells R_B_39]
set_false_path -from [get_pins U_A_40/Q] -to [get_pins U_B_40/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_40] -to [get_cells R_B_40]
set_false_path -from [get_pins U_A_41/Q] -to [get_pins U_B_41/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_41] -to [get_cells R_B_41]
set_false_path -from [get_pins U_A_42/Q] -to [get_pins U_B_42/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_42] -to [get_cells R_B_42]
set_false_path -from [get_pins U_A_43/Q] -to [get_pins U_B_43/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_43] -to [get_cells R_B_43]
set_false_path -from [get_pins U_A_44/Q] -to [get_pins U_B_44/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_44] -to [get_cells R_B_44]
set_false_path -from [get_pins U_A_45/Q] -to [get_pins U_B_45/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_45] -to [get_cells R_B_45]
set_false_path -from [get_pins U_A_46/Q] -to [get_pins U_B_46/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_46] -to [get_cells R_B_46]
set_false_path -from [get_pins U_A_47/Q] -to [get_pins U_B_47/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_47] -to [get_cells R_B_47]
set_false_path -from [get_pins U_A_48/Q] -to [get_pins U_B_48/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_48] -to [get_cells R_B_48]
set_false_path -from [get_pins U_A_49/Q] -to [get_pins U_B_49/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_49] -to [get_cells R_B_49]
set_false_path -from [get_pins U_A_50/Q] -to [get_pins U_B_50/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_50] -to [get_cells R_B_50]
set_false_path -from [get_pins U_A_51/Q] -to [get_pins U_B_51/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_51] -to [get_cells R_B_51]
set_false_path -from [get_pins U_A_52/Q] -to [get_pins U_B_52/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_52] -to [get_cells R_B_52]
set_false_path -from [get_pins U_A_53/Q] -to [get_pins U_B_53/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_53] -to [get_cells R_B_53]
set_false_path -from [get_pins U_A_54/Q] -to [get_pins U_B_54/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_54] -to [get_cells R_B_54]
set_false_path -from [get_pins U_A_55/Q] -to [get_pins U_B_55/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_55] -to [get_cells R_B_55]
set_false_path -from [get_pins U_A_56/Q] -to [get_pins U_B_56/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_56] -to [get_cells R_B_56]
set_false_path -from [get_pins U_A_57/Q] -to [get_pins U_B_57/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_57] -to [get_cells R_B_57]
set_false_path -from [get_pins U_A_58/Q] -to [get_pins U_B_58/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_58] -to [get_cells R_B_58]
set_false_path -from [get_pins U_A_59/Q] -to [get_pins U_B_59/D]
set_multicycle_path -setup 2 -hold 1 -from [get_cells R_A_59] -to [get_cells R_B_59]
