#!/usr/bin/env python3
"""
Phase 7 — Generate the SDC Command Support Matrix (markdown).

Classifies every command in the inventory:
  FULL      — recognized + all standard options interpreted
  PARTIAL   — recognized but some standard options silently ignored
  NETLIST   — meaningful validation requires design context
  UNSUPPORTED — standard SDC command no module parses

Usage:
    python benchmarks/generate_support_matrix.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from support_boundary import (
    RECOGNIZED_COMMANDS, STANDARD_OPTIONS, INTERPRETED_OPTIONS,
    STANDARD_UNRECOGNIZED, NETLIST_COLLECTION_FNS, TCL_EXECUTION_REQUIRED,
)

OUT = ROOT / "rta" / "evidence" / "support_matrix.md"


def classify(cmd: str) -> str:
    std = STANDARD_OPTIONS.get(cmd, set())
    interp = INTERPRETED_OPTIONS.get(cmd, set())
    uninterpreted = sorted(std - interp)
    if cmd not in RECOGNIZED_COMMANDS:
        return "UNSUPPORTED"
    if uninterpreted:
        return "PARTIAL"
    return "FULL"


def main():
    lines = [
        "# SDC Command Support Matrix (Phase 7)",
        "",
        "How completely the validator analyzes each SDC command. Generated by",
        "`benchmarks/generate_support_matrix.py` from `support_boundary.py`.",
        "",
        "| Command | Level | Interpreted options | Standard options silently ignored |",
        "|---|---|---|---|",
    ]
    for cmd in sorted(RECOGNIZED_COMMANDS | STANDARD_UNRECOGNIZED):
        std = STANDARD_OPTIONS.get(cmd, set())
        interp = INTERPRETED_OPTIONS.get(cmd, set())
        level = classify(cmd)
        ignored = sorted(std - interp)
        interp_s = ", ".join(sorted(interp)) or "—"
        ignored_s = ", ".join(ignored) or "—"
        lines.append(f"| `{cmd}` | {level} | {interp_s} | {ignored_s} |")

    lines += [
        "",
        "## Collection functions (NETLIST_REQUIRED by nature)",
        "",
        "These resolve against the design; SDC-only analysis cannot prove them:",
        "",
        "`" + "`, `".join(sorted(NETLIST_COLLECTION_FNS)) + "`",
        "",
        "## Tcl constructs (TCL_EXECUTION_REQUIRED — never executed)",
        "",
        "`" + "`, `".join(sorted(TCL_EXECUTION_REQUIRED)) + "`",
        "",
        "## Notes",
        "",
        "- **PARTIAL** means the command is recognized and its core semantics are",
        "  checked, but some standard options are silently ignored. The analysis",
        "  scope summary surfaces these per-run.",
        "- **UNSUPPORTED** means the command parses as plain text with no analysis.",
        "- Level is per-command; the per-run trust status is computed by",
        "  `support_boundary.analyze_scope()` and attached to every `CheckResult`.",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
