#!/usr/bin/env python3
"""
Phase 4 — Realistic SDC corpus.

Builds a set of representative SDC files that approximate real engineering SDC
style: multiple constraint types, Tcl variables, backslash multiline formatting,
braced collections, wildcards, comments — combined the way a real design team
writes them. Then feeds each through the three migrated modules (checker,
converter, clock_relations) and verifies core facts + no crashes.

Syntax patterns follow the Accellera SDC 2.1 command reference and common
tool conventions (see PHASE4_VARIABLE_AND_STRESS_REPORT.md).
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT))

from checker import check_sdc                 # noqa: E402
from converter import parse_sdc               # noqa: E402
from clock_relations import analyze_clock_relations  # noqa: E402

PASS = 0
FAIL = 0

REALISTIC_1 = r"""# ─────────────────────────────────────────────────────────────
# SoC top-level timing constraints — 3 clocks, 2 generated
# Generated by chip_flow 2026.1 — do not edit by hand
# ─────────────────────────────────────────────────────────────
set sdc_version 2.1
set_units -time ns -capacitance pF -resistance kohm -voltage V \
          -current mA

set CLK_PERIOD_CPU 2.0
set CLK_PERIOD_IO  10.0

# Primary clocks
create_clock -name clk_cpu -period $CLK_PERIOD_CPU \
    -waveform {0 1.0} [get_ports clk_cpu]
create_clock -name clk_io -period $CLK_PERIOD_IO \
    -waveform {0 5.0} [get_ports clk_io]

# Generated clocks (PLL + dividers)
create_generated_clock -name pll_2x -source [get_ports clk_cpu] \
    -multiply_by 2 [get_pins U_PLL/CLKOUT]
create_generated_clock -name div_4 -master_clock pll_2x \
    -source [get_pins U_PLL/CLKOUT] -divide_by 4 [get_pins U_DIV/CLK]

# Clock uncertainty (jitter + margins)
set_clock_uncertainty -setup 0.05 -hold 0.03 [get_clocks clk_cpu]
set_clock_uncertainty 0.2 [get_clocks clk_io]

# CDC — async domain crossings
set_clock_groups -asynchronous \
    -group [get_clocks {clk_cpu pll_2x div_4}] \
    -group [get_clocks clk_io]

# I/O timing
set_input_delay -max 0.5 -min 0.1 -clock clk_cpu \
    [get_ports {data_in*}]
set_input_delay -max 1.5 -min 0.3 -clock clk_io [get_ports rst_n]
set_output_delay -max 0.4 -min 0.05 -clock clk_cpu \
    [get_ports {data_out*}]
set_output_delay -max 2.0 -min 0.5 -clock clk_io [get_ports irq*]

# Input slew / drive modeling
set_driving_cell -lib_cell INV_X1 -clock clk_cpu [all_inputs]
set_input_transition 0.08 [get_ports {data_in*}]
set_load 0.5 [all_outputs]

# Timing exceptions
set_false_path -from [get_clocks clk_io] -to [get_clocks clk_cpu]
set_false_path -from [get_ports scan_en] -to [all_registers] \
    -setup -hold
set_multicycle_path -setup 3 -from [get_ports data_in*] \
    -to [get_pins U_DIV/*/D]
set_multicycle_path -hold 2 -from [get_ports data_in*] \
    -to [get_pins U_DIV/*/D]
set_max_delay 2.5 -datapath_only -from [get_ports data_in*] \
    -to [get_pins U_DIV/*/D]

# DFT
set_case_analysis 1 [get_ports test_mode]
set_disable_timing -from U_A -to U_B

# Design rules
set_max_transition 0.3 [get_clocks clk_cpu]
set_max_capacitance 1.0 [all_outputs]
set_max_fanout 20 [all_inputs]
set_operating_conditions SSG0P72V125C
"""

REALISTIC_2 = r"""# Memory interface constraints — DDR style
set sdc_version 2.1
create_clock -name ddr_clk -period 1.875 \
    -waveform {0 0.9375} [get_ports ddr_ck]
create_clock -name ddr_clk_n -period 1.875 \
    -waveform {0.9375 1.875} [get_ports ddr_ck_n]

set_clock_uncertainty -setup 0.09 -hold 0.06 [get_clocks ddr_clk]

set_output_delay -max 0.6 -min 0.2 -clock ddr_clk \
    [get_ports {dq[0] dq[1] dq[2] dq[3]}]
set_output_delay -max 0.6 -min 0.2 -clock ddr_clk \
    [get_ports {dm[0] dm[1]}]
set_input_delay -max 0.5 -min 0.15 -clock ddr_clk \
    [get_ports {dq[0] dq[1] dq[2] dq[3]}]

set_false_path -from [get_clocks ddr_clk] -to [get_clocks ddr_clk_n]
set_multicycle_path -setup 2 -hold 1 \
    -from [get_ports {dq[*]}] -to [get_ports {dq[*]}]
"""


def ok(cond, msg):
    if not cond:
        raise AssertionError(msg)


def run(name, text, checks):
    """checks = list of (description, callable(r, p, cr))."""
    global PASS, FAIL
    try:
        r = check_sdc(text)
        p = parse_sdc(text, name)
        cr = analyze_clock_relations(text)
        for desc, fn in checks:
            fn(r, p, cr)
        PASS += 1
        print(f"  ✅ {name} — {len(checks)} facts verified, no crash")
    except AssertionError as exc:
        FAIL += 1
        print(f"  ❌ {name}: {exc}")
    except Exception as exc:  # noqa: BLE001
        FAIL += 1
        print(f"  💥 {name}: {type(exc).__name__}: {exc}")


def soctop_checks():
    return [
        ("no unexpected errors",
         lambda r, p, cr: ok(
             not r.errors or {i.code for i in r.errors} <= {"SDC-005", "SDC-006"},
             f"unexpected errors: {sorted({i.code for i in r.errors})}")),
        ("checker: 2 primary + 2 generated clocks",
         lambda r, p, cr: ok(r.stats["Clocks"] == 2 and r.stats["Generated clocks"] == 2,
                             f"clocks={r.stats['Clocks']} gen={r.stats['Generated clocks']}")),
        ("converter: clk_cpu period 2.0 from $CLK_PERIOD_CPU",
         lambda r, p, cr: ok(next(c.period for c in p.clocks if c.name == "clk_cpu") == 2.0,
                             "clk_cpu period wrong")),
        ("converter: pll_2x period derived (2.0 * 1/2 = 1.0)",
         lambda r, p, cr: ok(abs(next(c.period for c in p.clocks if c.name == "pll_2x") - 1.0) < 1e-9,
                             f"pll_2x={[ (c.name,c.period) for c in p.clocks if 'pll' in c.name ]}")),
        ("clock relations: 4 clocks, 6 pairs, no crash",
         lambda r, p, cr: ok(len(cr.clocks) == 4 and len(cr.pairs) == 6,
                             f"clocks={len(cr.clocks)} pairs={len(cr.pairs)}")),
        ("clock relations: clk_io async vs clk_cpu group",
         lambda r, p, cr: ok(cr.stats.get("missing", -1) >= 0, "missing stats missing")),
    ]


def ddr_checks():
    return [
        ("no crash, ddr clocks parsed",
         lambda r, p, cr: ok(len([c for c in p.clocks if c.name.startswith("ddr")]) == 2,
                             "ddr clocks not parsed")),
        ("ddr_clk period 1.875",
         lambda r, p, cr: ok(abs(next(c.period for c in p.clocks if c.name == "ddr_clk") - 1.875) < 1e-9,
                             "ddr period wrong")),
        ("bracketed bus port list {dq[0]..dq[3]} accepted",
         lambda r, p, cr: ok(len(p.input_delays) >= 1, "no input delay parsed")),
        ("clock relations 1 pair",
         lambda r, p, cr: ok(len(cr.pairs) == 1, f"pairs={len(cr.pairs)}")),
    ]


def main():
    print("PHASE 4 REALISTIC SDC CORPUS")
    run("realistic_soctop.sdc", REALISTIC_1, soctop_checks())
    run("realistic_ddr.sdc", REALISTIC_2, ddr_checks())
    print(f"\nCORPUS: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL else 0)


if __name__ == "__main__":
    main()
