"""Ṛta brand + Unicode verification.

Guards the identity migration:
  - the visible brand is the Unicode "Ṛta" (never a plain "Rta" on user surfaces)
  - the technical ASCII identifier "rta" exists (CLI alias, cmd shim)
  - the old proper-noun product names are gone from migrated surfaces
  - legitimate SDC terminology is preserved (SDC-046, check_sdc, sdc-tools alias)
  - Unicode survives CLI stdout, generated SDC, HTML reports, and metadata
"""

import os
import subprocess
import sys

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CLI = os.path.join(ROOT, "cli.py")
BRAND = "Ṛta"


def _read(rel):
    with open(os.path.join(ROOT, rel), encoding="utf-8") as f:
        return f.read()


def _run_cli(*args):
    return subprocess.run(
        [sys.executable, CLI, *args],
        capture_output=True, timeout=60,
    )


class TestVisibleBrand:
    """The Unicode brand must appear on every user-facing surface."""

    def test_readme_brand_and_cli(self):
        readme = _read("README.md")
        assert BRAND in readme
        assert "rta check design.sdc" in readme

    def test_website_brand(self):
        idx = _read("rta/website/index.html")
        assert f"<title>{BRAND}" in idx
        assert BRAND in idx

    def test_workspace_brand(self):
        idx = _read("rta/workspace/webui/index.html")
        assert f"<title>{BRAND}" in idx
        assert "Ṛ<b>ta</b>" in idx

    def test_cli_version_unicode(self):
        r = _run_cli("--version")
        assert r.returncode == 0
        out = r.stdout.decode("utf-8", errors="replace")
        assert BRAND in out and "1.3.0" in out

    def test_report_html_brand(self):
        from reporter import _page
        html = _page("t", "s", "<p>x</p>")
        assert BRAND in html

    def test_generated_sdc_brand(self):
        from generator import SDCParams, ClockDef, generate_sdc
        p = SDCParams(design_name="TOP", sdc_version="2.2",
                      clocks=[ClockDef(name="clk", clk_type="primary",
                                       port="clk", period=10.0)])
        sdc = generate_sdc(p)
        assert "generated by Ṛta" in sdc

    def test_package_metadata_brand(self):
        pyproject = _read("pyproject.toml")
        assert BRAND in pyproject


class TestAsciiIdentifier:
    """The technical ASCII identifier `rta` must exist and stay ASCII."""

    def test_pyproject_rta_entry_point(self):
        pyproject = _read("pyproject.toml")
        assert 'rta = "cli:main"' in pyproject
        assert 'sdc-tools = "cli:main"' in pyproject  # alias preserved

    def test_rta_cmd_shim(self):
        assert os.path.exists(os.path.join(ROOT, "rta.cmd"))

    def test_technical_names_ascii(self):
        # Package/wheel/import identifiers remain ASCII (no Unicode in them).
        pyproject = _read("pyproject.toml")
        assert 'name = "sdc-tools"' in pyproject
        # Console-script entry-point lines must be ASCII-safe.
        scripts = pyproject.split("[project.scripts]")[1].split("[tool.setuptools]")[0]
        for line in scripts.splitlines():
            if "=" in line and "cli:main" in line:
                assert line.startswith("sdc-tools") or line.startswith("rta"), line


class TestLegacyNamesRemoved:
    """Proper-noun legacy names are gone from migrated surfaces."""

    SURFACES = (
        ["README.md", "cli.py", "reporter.py", "generator.py", "api_server.py",
         "legacy/streamlit/app.py", "rta/workspace/webui/index.html",
         "rta/website/index.html", "rta/website/assets/js/site.js",
         "rta/docs/rta/BRAND_FOUNDATION.md", "rta/docs/rta/PRODUCT_TAXONOMY.md"]
        + [f"rta/website/capabilities/{f}" for f in os.listdir("rta/website/capabilities") if f.endswith(".html")]
        + [f"ui/{f}" for f in os.listdir("ui") if f.endswith(".py")]
        + [f"rta/workspace/webui/assets/js/{f}" for f in os.listdir("rta/workspace/webui/assets/js") if f.endswith(".js")]
        + [f"rta/docs/features/{f}" for f in os.listdir("rta/docs/features") if f.endswith(".md")]
    )

    @pytest.mark.parametrize("rel", SURFACES)
    def test_no_legacy_proper_noun(self, rel):
        text = _read(rel)
        assert "SDC Validator" not in text, rel
        assert "SDC Tools" not in text, rel


class TestSdcTerminologyPreserved:
    """The SDC standard's terminology must never be branded away."""

    def test_rule_codes_intact(self):
        from rules_registry import get_rule
        assert get_rule("SDC-046") is not None
        assert get_rule("SDC-008") is not None

    def test_checker_api_intact(self):
        from checker import check_sdc
        r = check_sdc("create_clock -name clk -period 5.0 [get_ports clk]\n"
                      "set_input_delay -max 6.0 -clock clk [get_ports din]\n")
        assert any(i.code == "SDC-008" for i in r.issues)

    def test_docs_refer_to_sdc_not_rta_language(self):
        readme = _read("README.md")
        assert "SDC file" in readme
        # Product modules use Ṛta, the standard keeps SDC.
        assert "Ṛta Validate" in readme
